kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    # use argocd to patch this annotation on the generated serviceaccount
    serviceaccounts.openshift.io/oauth-redirecturi.first: 'https://cryostat-istio-ingress.apps.cluster-mqlh6.dynamic.redhatworkshops.io'
  name: cryostat
  namespace: cryostat
